In [1]:
import seaborn as sns
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split

In [18]:
titanic_data = sns.load_dataset("titanic")
titanic_data.head()
titanic_data.describe
titanic_data.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
titanic_data.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
features = ["pclass","age","sex","fare","embarked"]
target = ["survived"]

In [21]:
## Handle missing values 
from sklearn.impute import SimpleImputer
imp_median = SimpleImputer(strategy="median")
imp_mode = SimpleImputer(strategy="most_frequent")

titanic_data["age"]= imp_median.fit_transform(titanic_data[["age"]]).ravel() ## imputer retyrns 2d df ravel converts it into (n,1)=>(n)
titanic_data["embarked"]= imp_mode.fit_transform(titanic_data[["embarked"]]).ravel()

In [22]:
titanic_data.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [24]:
## Encode our features
titanic_data.head()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

titanic_data["sex"] = le.fit_transform(titanic_data["sex"])
titanic_data["embarked"] = le.fit_transform(titanic_data["embarked"])

In [27]:
titanic_data["embarked"].dtype
titanic_data["sex"].dtype

dtype('int64')

In [30]:
X = titanic_data[features]
y = titanic_data[target]

In [31]:
X_train , X_test , y_train, y_test = train_test_split(X , y , test_size=0.2, random_state=42)

In [33]:
X_train.head()

     pclass   age  sex     fare  embarked
331       1  45.5    1  28.5000         2
733       2  23.0    1  13.0000         2
382       3  32.0    1   7.9250         2
704       3  26.0    1   7.8542         2
813       3   6.0    0  31.2750         2

In [34]:
y_train.head()

     survived
331         0
733         0
382         0
704         0
813         0