In [20]:
from sklearn.svm import SVC
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
df = datasets.load_iris(as_frame=True).frame

In [15]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [17]:
X = df.drop("target",axis=1)
y = df["target"]

In [18]:
X.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [19]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [30]:
X_train , X_test , y_train , y_test = train_test_split(X,y,random_state=42,test_size=0.3,stratify=y)

In [31]:
X_train.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
98                 5.1               2.5                3.0               1.1
68                 6.2               2.2                4.5               1.5
19                 5.1               3.8                1.5               0.3
143                6.8               3.2                5.9               2.3
99                 5.7               2.8                4.1               1.3

In [32]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled

array([[-1.47393679,  1.20365799, -1.56253475, -1.31260282],
       [-0.13307079,  2.99237573, -1.27600637, -1.04563275],
       [ 1.08589829,  0.08570939,  0.38585821,  0.28921757],
       [-1.23014297,  0.75647855, -1.2187007 , -1.31260282],
       [-1.7177306 ,  0.30929911, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.72969227,  0.95664273],
       [ 0.72020757,  0.30929911,  0.44316389,  0.4227026 ],
       [-0.74255534,  0.98006827, -1.27600637, -1.31260282],
       [-0.98634915,  1.20365799, -1.33331205, -1.31260282],
       [-0.74255534,  2.32160658, -1.27600637, -1.44608785],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993,  0.75647855,  0.44316389,  0.55618763],
       [ 1.08589829,  0.08570939,  0.55777524,  0.4227026 ],
       [-0.49876152,  1.87442714, -1.39061772, -1.04563275],
       [-0.49876152,  1.4272477 , -1.27600637, -1.31260282],
       [-0.37686461, -1.47941864, -0.01528151, -0.24472256],
       [ 0.59831066, -0.58505976,  0.78699794,  0.4227026 ],
       [ 0.72020757,  0.08570939,  1.01622064,  0.8231577 ],
       [ 0.96400139, -0.13788033,  0.38585821,  0.28921757],
       [ 1.69538284,  1.20365799,  1.3600547 ,  1.75755292],
       [-0.13307079, -0.36147005,  0.27124686,  0.15573254],
       [ 2.18297047, -0.13788033,  1.64658307,  1.22361279],
       [-0.2549677 , -0.13788033,  0.44316389,  0.4227026 ],
       [-0.86445224,  0.98006827, -1.33331205, -1.31260282],
       [ 2.30486738, -0.58505976,  1.70388875,  1.09012776],
       [-0.01117388, -0.80864948,  0.21394119, -0.24472256],
       [-0.74255534,  0.75647855, -1.33331205, -1.31260282],
       [-0.98634915,  0.98006827, -1.39061772, -1.17911778],
       [-0.86445224,  1.65083742, -1.04678367, -1.04563275],
       [-0.98634915, -2.37377751, -0.12989286, -0.24472256],
       [ 0.59831066, -0.80864948,  0.67238659,  0.8231577 ],
       [-1.23014297,  0.75647855, -1.04678367, -1.31260282],
       [-0.98634915, -0.13788033, -1.2187007 , -1.31260282],
       [-0.86445224,  0.53288883, -1.16139502, -0.91214772],
       [-0.2549677 , -0.80864948,  0.27124686,  0.15573254],
       [-0.86445224,  0.75647855, -1.27600637, -1.31260282],
       [-0.13307079, -0.13788033,  0.27124686,  0.02224751],
       [ 2.30486738,  1.65083742,  1.70388875,  1.35709783],
       [-1.47393679,  0.30929911, -1.33331205, -1.31260282],
       [ 0.47641375, -0.36147005,  0.32855254,  0.15573254],
       [-0.13307079, -1.25582892,  0.72969227,  1.09012776],
       [-0.37686461,  2.5451963 , -1.33331205, -1.31260282],
       [ 0.23261993, -0.13788033,  0.61508092,  0.8231577 ],
       [-0.01117388, -0.80864948,  0.78699794,  0.95664273],
       [ 0.23261993, -1.92659808,  0.15663551, -0.24472256],
       [-0.49876152, -0.13788033,  0.44316389,  0.4227026 ],
       [ 0.47641375,  0.75647855,  0.95891497,  1.49058286],
       [-0.37686461, -1.70300836,  0.15663551,  0.15573254],
       [-0.49876152,  1.87442714, -1.16139502, -1.04563275],
       [-0.98634915, -1.70300836, -0.24450422, -0.24472256],
       [ 0.72020757, -0.80864948,  0.90160929,  0.95664273],
       [-0.98634915,  0.53288883, -1.33331205, -1.31260282],
       [-0.98634915,  0.30929911, -1.4479234 , -1.31260282],
       [-0.37686461, -1.47941864,  0.04202416, -0.11123753],
       [ 1.08589829, -0.13788033,  0.72969227,  0.68967267],
       [-1.10824606,  0.08570939, -1.27600637, -1.31260282],
       [-0.01117388, -0.58505976,  0.78699794,  1.62406789],
       [-0.98634915,  0.75647855, -1.27600637, -1.31260282],
       [-0.98634915,  0.98006827, -1.2187007 , -0.77866269],
       [ 0.11072303,  0.30929911,  0.61508092,  0.8231577 ],
       [-0.86445224, -1.25582892, -0.41642124, -0.11123753],
       [ 1.32969211,  0.30929911,  1.130832  ,  1.49058286],
       [ 0.23261993, -0.80864948,  0.78699794,  0.55618763],
       [ 0.35451684, -1.0322392 ,  1.07352632,  0.28921757],
       [ 2.30486738, -0.13788033,  1.3600547 ,  1.49058286],
       [-0.37686461, -1.25582892,  0.15663551,  0.15573254],
       [-1.7177306 , -0.36147005, -1.33331205, -1.31260282],
       [-1.83962751, -0.13788033, -1.50522907, -1.44608785],
       [ 0.23261993, -1.92659808,  0.72969227,  0.4227026 ],
       [ 1.69538284,  0.30929911,  1.30274902,  0.8231577 ],
       [-1.47393679,  0.08570939, -1.27600637, -1.31260282],
       [-0.86445224,  0.98006827, -1.33331205, -1.17911778],
       [-1.7177306 , -0.13788033, -1.39061772, -1.31260282],
       [ 0.59831066, -1.25582892,  0.67238659,  0.4227026 ],
       [ 0.59831066,  0.75647855,  1.07352632,  1.62406789],
       [-1.47393679,  0.75647855, -1.33331205, -1.17911778],
       [ 1.2077952 , -0.13788033,  1.01622064,  1.22361279],
       [ 0.59831066,  0.53288883,  1.30274902,  1.75755292],
       [-1.35203988,  0.30929911, -1.39061772, -1.31260282],
       [ 0.35451684, -0.36147005,  0.55777524,  0.28921757],
       [ 0.84210448, -0.58505976,  0.50046957,  0.4227026 ],
       [ 0.47641375, -0.58505976,  0.61508092,  0.8231577 ],
       [ 1.45158902,  0.30929911,  0.55777524,  0.28921757],
       [ 0.72020757,  0.30929911,  0.90160929,  1.49058286],
       [-0.86445224,  1.65083742, -1.2187007 , -1.31260282],
       [ 1.32969211,  0.08570939,  0.95891497,  1.22361279],
       [ 0.11072303, -0.13788033,  0.27124686,  0.4227026 ],
       [ 0.84210448, -0.13788033,  0.84430362,  1.09012776],
       [-0.13307079, -1.0322392 , -0.12989286, -0.24472256],
       [-0.74255534, -0.80864948,  0.09932984,  0.28921757],
       [ 0.35451684, -0.13788033,  0.50046957,  0.28921757],
       [-1.5958337 , -1.70300836, -1.39061772, -1.17911778],
       [ 0.96400139, -0.36147005,  0.50046957,  0.15573254],
       [-0.37686461, -1.0322392 ,  0.38585821,  0.02224751],
       [-0.62065843,  1.4272477 , -1.27600637, -1.31260282],
       [-0.2549677 , -0.13788033,  0.21394119,  0.15573254],
       [ 1.81727975, -0.36147005,  1.47466605,  0.8231577 ],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.22361279],
       [-0.86445224,  1.4272477 , -1.27600637, -1.04563275],
       [-1.10824606, -1.47941864, -0.24450422, -0.24472256],
       [ 1.08589829,  0.53288883,  1.130832  ,  1.75755292],
       [ 1.69538284, -0.13788033,  1.18813767,  0.55618763],
       [-1.10824606,  1.20365799, -1.33331205, -1.44608785],
       [ 1.08589829,  0.08570939,  1.07352632,  1.62406789],
       [-1.10824606, -0.13788033, -1.33331205, -1.31260282],
       [ 1.32969211,  0.08570939,  0.67238659,  0.4227026 ],
       [ 1.93917666, -0.58505976,  1.3600547 ,  0.95664273],
       [ 0.59831066, -0.36147005,  1.07352632,  0.8231577 ],
       [-0.13307079, -0.58505976,  0.21394119,  0.15573254],
       [ 0.84210448, -0.13788033,  1.01622064,  0.8231577 ],
       [ 0.59831066, -1.70300836,  0.38585821,  0.15573254],
       [ 0.72020757, -0.36147005,  0.32855254,  0.15573254],
       [-0.2549677 , -0.58505976,  0.67238659,  1.09012776],
       [ 0.11072303, -0.13788033,  0.78699794,  0.8231577 ],
       [-0.49876152,  0.75647855, -1.16139502, -1.31260282],
       [ 0.35451684, -0.58505976,  0.15663551,  0.15573254],
       [-1.10824606, -1.25582892,  0.44316389,  0.68967267],
       [-0.01117388,  2.09801686, -1.4479234 , -1.31260282],
       [-0.01117388, -1.0322392 ,  0.15663551,  0.02224751],
       [ 1.57348593, -0.13788033,  1.24544335,  1.22361279]])

In [33]:
## for default rbf kernal
svc = SVC()
svc.fit(X_train_scaled, y_train)

SVC()

In [28]:
from sklearn.metrics import accuracy_score , f1_score

In [34]:
y_pred = svc.predict(X_test_scaled)
print("Accuracy score:",accuracy_score(y_test,y_pred))

Accuracy score: 0.9333333333333333

In [36]:
## for linear kernal 
svc = SVC(kernel="linear")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy score:",accuracy_score(y_test,y_pred))

Accuracy score: 0.9111111111111111

In [37]:
## for polynomial kernal 
svc = SVC(kernel="poly")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy score:",accuracy_score(y_test,y_pred))

Accuracy score: 0.8666666666666667

In [38]:
## for sigmoid kernal 
svc = SVC(kernel="sigmoid")
svc.fit(X_train_scaled, y_train)
y_pred = svc.predict(X_test_scaled)
print("Accuracy score:",accuracy_score(y_test,y_pred))

Accuracy score: 0.9111111111111111